-- return {
--   {
--     "stevearc/conform.nvim",
--     dependencies = { "mason.nvim" },
--     lazy = true,
--     cmd = "ConformInfo",
--     keys = {
--       {
--         "<leader>cF",
--         function()
--           require("conform").format({ formatters = { "injected" } })
--         end,
--         mode = { "n", "v" },
--         desc = "Format Injected Langs",
--       },
--     },
--     opts = {
--       format = {
--         timeout_ms = 3000,
--         async = false, -- not recommended to change
--         quiet = false, -- not recommended to change
--       },
--       formatters_by_ft = {
--         lua = { "stylua" },
--         fish = { "fish_indent" },
--         sh = { "shfmt" },
--       },
--       formatters = {
--         injected = { options = { ignore_errors = true } },
--         -- # Example of using dprint only when a dprint.json file is present
--         -- dprint = {
--         --   condition = function(ctx)
--         --     return vim.fs.find({ "dprint.json" }, { path = ctx.filename, upward = true })[1]
--         --   end,
--         -- },
--         --
--         -- # Example of using shfmt with extra args
--         -- shfmt = {
--         --   prepend_args = { "-i", "2", "-ci" },
--         -- },
--       },
--     },
--     config = function (_, opts)
--       require("conform").setup(opts)
--     end
--   }
-- }
return {}
